/**
 * @overview Litemint Pepper resources languages implementation.
 * @copyright 2018-2019 Frederic Rezeau.
 * @copyright 2018-2019 Litemint LLC.
 * @license [MIT]{@link https://github.com/litemint/litemint/blob/master/LICENSE}
 */

(function (namespace) {
    "use strict";

    /**
     * Language pack for English.
     * @member englishLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const englishLanguagePack = [
        "Create New PIN",
        "Enter your PIN",
        "Confirm your PIN",
        "Sign In",
        "Next",
        "The crypto world is limitless, explore it.",
        "Incorrect PIN. Please try again.",
        "Your PIN can be 4-12 digits.",
        "Make sure you choose one that's hard to guess.",
        "Options",
        "Switch accounts", // 10
        "Create account",
        "Import account",
        "Select language",
        "Help & feedback",
        "Configuring language. Please wait...",
        "Loading your account. Please wait...",
        "Account",
        "Loading your account. Please wait...",
        "SAVE YOUR BACKUP PHRASE",
        "Please write down these 24 words on a paper.", // 20
        "If you lose your PIN or device",
        "these words allow you to restore your funds.",
        "OK",
        "Write",
        "Verify",
        "Finish",
        "Next Step",
        "Close",
        "Type your words in the same order (1-24).",
        "Use a space to separate each word", //30
        "SUCCESS!",
        "FAILED!",
        "Your backup phrase was not validated.",
        "Your account is not backed-up.",
        "Make sure you write all words from 1 to 24.",
        "Keep your backup phrase secret!",
        "Use these 24 words to recover your funds",
        "in case of loss or forgotten PIN.",
        "Made with love",
        "Balance", // 40
        "Loading...",
        "Verified",
        "Unverified",
        "Send",
        "Receive",
        "Trade",
        "Activity",
        "Assets",
        "Reserve:",
        "Balance:", // 50
        "Amount to send:",
        "Enter your destination address",
        "Enter your memo (optional)",
        "Invalid Amount",
        "Invalid Address",
        "Available balance:",
        "You are sending:",
        "Fee:",
        "minute ago",
        "minutes ago", // 60
        "Few seconds ago",
        "Add",
        "Asset Added",
        "Asset Removed",
        "Your payment was successful.",
        "Your payment was not successful.",
        "Verify the destination address",
        "and try again.",
        "The transaction receipt will shortly",
        "be added to the Activity List.", // 70
        "Partner",
        "Asset to receive:",
        "You can also receive this asset with your XLM address.",
        "You can receive any asset with your XLM address.",
        "Tap to copy address",
        "Select Asset",
        "Details",
        "Price Chart",
        "Share",
        "Website", // 80
        "Remove Asset",
        "Verified",
        "Trusted",
        "Non-zero Balance",
        "Payment Received",
        "Payment Sent",
        "Trades",
        "Trustlines",
        "Other",
        "Sign Out", // 90
        "Manage Account",
        "Developed by: ",
        "Distributed by: ",
        "License: ",
        "Dependency Licenses",
        "Warning",
        "Trading involves significant risk and can result in the loss of your invested capital. You should not invest more than you can afford to lose and should ensure that you fully understand the risks involved.",
        "Legal Links",
        "Term of Use",
        "Privacy Policy", //100
        "Help",
        "Support: ",
        "Security: ",
        "View on Github",
        "This project source code is available on Github.",
        "Your wallet is empty,",
        "Time to nag your friends.",
        "Connection error. Retrying...",
        "Asset Allowed",
        "Asset Disallowed", // 110
        "Options Changed",
        "Data Changed",
        "Sequence Bumped",
        "Account Merged",
        "Sell Order",
        "Cancel Sell Order",
        "Path Payment",
        "Watch Only Account",
        "No Data Available.",
        "(24H)", // 120
        "The QR code data was copied to clipboard.",
        "The address was copied to clipboard.",
        "Memo Copied:",
        "Enter issuer domain name",
        "Wait...",
        "Code:",
        "Asset Issuer:",
        "Description:",
        "Conditions:",
        "Lumens are the native asset of the Stellar network. One lumen (XLM) is a unit of digital currency, like a bitcoin.", // 130
        "Lumen supply is determined by fixed, protocol-level rules. The number of lumens created at genesis was 100 billion. Every year, there is a 1% inflation rate. New lumens cannot be generated arbitrarily by anyone.",
        "Adding disabled. Not enough XLM reserve.",
        "Issuer:",
        "My Address:",
        "Share via",
        "Enter a private key, public address or",
        "24-word backup phrase to import an account.",
        "Account Settings",
        "Save your backup phrase",
        "Rename Account", // 140
        "Delete Account",
        "Are you sure? Tap to confirm.",
        "Are you really sure?",
        "Last chance! Tap to delete account.",
        "Deleting...",
        "Enter new account name",
        "Quote Currency",
        "Import Account",
        "Enter a valid account",
        "IMPORT AN ACCOUNT",//150
        "Importing: ",
        "Recent Addresses",
        "Payment Received: ",
        "Notifications",
        "Toasts",
        "Get Your Friendly Address",
        "Marketplace"
    ];

    /**
     * Language pack for German.
     * @member germanLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const germanLanguagePack = [
        "Neue PIN erzeugen",
        "PIN eingeben",
        "PIN bestätigen",
        "Einloggen",
        "Weiter",
        "Krypto ist grenzenlos, erforsche es.",
        "Falsche PIN. Nochmal versuchen.",
        "Die PIN kann zw. 4-12 Zahlen lang sein.",
        "Wähle eine PIN, welche schwer zu erraten ist.",
        "Optionen",
        "Konto wechseln", // 10
        "Konto erzeugen",
        "Konto importieren",
        "Sprache wählen",
        "Hilfe & Rückmeldung",
        "Konfiguriere Sprache, bitte warten...",
        "Konto wird geladen, bitte warten...",
        "Konto",
        "Konto wird geladen, bitte warten...",
        "SICHERE DEINE WIEDERHERSTELLUNGS-PHRASE",
        "Schreibe die nächsten 24 Wörter auf Papier.", // 20
        "Falls du dein Gerät oder die PIN verlierst",
        "können diese Wörter dein Konto wiederherstellen.",
        "OK",
        "Schreibe",
        "Verifiziere",
        "Beende",
        "Nächster Schritt",
        "Schließen",
        "Tippe die Wörter in gleicher Reihenfolge (1-24).",
        "Benutze ein Leerzeichen zw. den Wörtern", //30
        "ERFOLGREICH!",
        "FEHLGESCHLAGEN!",
        "Wiederherstellungs-Phrase nicht bestätigt.",
        "Dein Konto ist nicht gesichert.",
        "Schreibe alle Wörter von 1-24.",
        "Halte deine Wiederherstellungs-Phrase geheim!",
        "Benutze die 24 Wörter um dein Konto wiederherzustellen.",
        "falls du dein Gerät oder die PIN verlierst.",
        "Mit Liebe gemacht",
        "Guthaben", // 40
        "Lade...",
        "Verifiziert",
        "Nicht verifiziert",
        "Senden",
        "Empfangen",
        "Tauschen",
        "Aktivitäten",
        "Währungen",
        "Reserve:",
        "Guthaben:", // 50
        "Betrag zu senden:",
        "Empfangsadresse eingeben",
        "Notiz einfügen (optional)",
        "Ungültiger Betrag",
        "Ungültige Adresse",
        "Verfügbares Guthaben",
        "Sie senden:",
        "Gebühr:",
        "Minute",
        "Minuten", // 60
        "vor ein paar Sekunden",
        "Hinzufügen",
        "Währung hinzugefügt",
        "Währung entfernt",
        "Deine Zahlung war erfolgreich.",
        "Deine Zahlung ist fehlgeschlagen.",
        "Überprüfen die Empfangsadresse",
        "und versuche es nochmal.",
        "Der Transaktionsempfang wird bald",
        "in deiner Aktivitätenliste aufscheinen.", // 70
        "Partner",
        "Empfangswährung:",
        "Sie können diese Währung mit der XML Adressee empfangen.",
        "Sie können jegliche Währung mit der XML Adressee empfangen.",
        "Berühren, um Adresse zu kopieren",
        "Währung wählen",
        "Details",
        "Kursdiagramm",
        "Teilen",
        "Webseite", // 80
        "Währung entfernen",
        "Verifiziert",
        "Vertrauenswürdig",
        "Leere Guthaben ausblenden",
        "Zahlung empfangen",
        "Zahlung gesendet",
        "Handel",
        "Vertrauenslinien",
        "Andere",
        "Ausloggen", // 90
        "Konto verwalten",
        "Entwickelt von: ",
        "Verteilt von: ",
        "Lizenz: ",
        "Abhängigkeitslizenzen",
        "Warnung",
        "Der Handel ist mit erheblichen Risiken verbunden und kann zum Verlust Ihres investierten Kapitals führen. Sie sollten nicht mehr investieren, als Sie sich leisten können, und sicherstellen, dass Sie die damit verbundenen Risiken vollständig verstehen.",
        "Rechtliche Links",
        "Nutzungsbedinungen",
        "Datenschutzbestimmungen", //100
        "Hilfe",
        "Support: ",
        "Sicherheit: ",
        "Auf Github anzeigen",
        "Der Quellcode dieses Projektes ist auf Github einsehbar.",
        "Deine Geldbörse ist leer,",
        "Es wird Zeit, deine Freunde anzupumpen.",
        "Verbindungsfehler, wiederhole... ",
        "Währung erlaubt",
        "Währung verboten", // 110
        "Optionen geändert",
        "Daten geändert",
        "Sequenz angestoßen",
        "Konten zusammengeführt",
        "Verkaufsauftrag",
        "Verkauf abbrechen",
        "Pfadzahlung",
        "Beobachtungskonto",
        "Keine Daten verfügbar",
        "(24H)", // 120
        "Der QR code wurde in die Zwischenablage kopiert.",
        "Die Adresse wurde in die Zwischenablage kopiert.",
        "Notiz kopiert:",
        "Ausstellers Domainname eingeben",
        "Warte...",
        "Code:",
        "Herausgeber:", //previous: "Ausstellers Währung"
        "Beschreibung:",
        "Konditionen:",
        "Lumen sind die eigentliche Währung des Stellar Netzwerkes. Ein Lumen (XML) ist eine Einheit dieser digitalen Währung, so wie Bitcoin.", // 130
        "Anzahl der Lumen ist durch feste Regeln auf Protokollebene bestimmt. Die Anzahl bei der Entstehung erzeugten Lumen betrug 100 Milliarden. Jedes Jahr beträgt die Inflationsrate 1%. Neue Lumen können von niemandem beliebig generiert werden.",
        "Hinzufügen deaktiviert. Nicht genügend XML.",
        "Aussteller:",
        "Ihre Adresse:",
        "Teilen mit",
        "Einen Privaten Schlüssel, Öffentliche Adresse oder die",
        "24 Wörter der Wiederherstellungs-Phrase eingeben um ein Konto zu importieren.",
        "Kontoeinstellungen",
        "Sichern Sie ihre Wiederherstellungs-Phrase",
        "Konto umbenennen", // 140
        "Konto löschen",
        "Sind Sie sicher? Zur Bestätigung berühren.",
        "Sind Sie sich wirklich sicher?",
        "Letzte Chance! Hier berühren um zu bestätigen.",
        "Lösche...",
        "Neuen Kontonamen eingeben",
        "Währung wählen",
        "Konto importieren",
        "Gültiges Konto eingeben",
        "KONTO IMPORTIEREN",//150
        "Importiere: ",
        "Letzte Adressen",
        "Zahlung erhalten: ",
        "Benachrichtigungen",
        "Toasts",
        "Ihre einfache Adresse bekommen",
        "Marktplatz"
    ];

    /**
     * Language pack for French.
     * @member frenchLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const frenchLanguagePack = [
        "Créer un nouveau code PIN",
        "Entrez votre code PIN",
        "Confirmez votre code PIN",
        "Se connecter",
        "Suivant",
        "Pour un monde crypto sans limite, à explorer.",
        "Code PIN incorrect. Veuillez réessayer.",
        "Votre code PIN peut être composé de 4 à 12 chiffres.",
        "Assurez-vous d'en choisir un difficile à deviner.",
        "Options",
        "Changer de compte",
        "Créer un compte",
        "Importer un compte",
        "Choisir la langue",
        "Aide et commentaires",
        "Configuration de la langue. Veuillez patienter ...",
        "Chargement de votre compte. Veuillez patienter ...",
        "Compte",
        "Chargement de votre compte. Veuillez patienter ...",
        "SAUVEZ VOTRE PHRASE SECRETE",
        "S'il vous plaît écrivez ces 24 mots sur un papier.",
        "Si vous perdez votre code PIN ou votre appareil",
        "Ces mots vous permettent de restaurer vos fonds.",
        "OK",
        "Écrire",
        "Vérifier",
        "Terminer",
        "Etape suivante",
        "Fermer",
        "Tapez vos mots dans le même ordre (1-24).",
        "Utilisez un espace pour séparer chaque mot",
        "SUCCÈS!",
        "ÉCHEC!",
        "Votre phrase de sauvegarde n'a pas été validée.",
        "Votre compte n'est pas sauvegardé.",
        "Assurez-vous d'écrire tous les mots de 1 à 24.",
        "Gardez votre phrase de sauvegarde secrète!",
        "Utilisez ces 24 mots pour récupérer vos fonds",
        "en cas de perte ou de code PIN oublié.",
        "Made with Love",
        "Balance",
        "Chargement...",
        "Vérifié",
        "Non vérifié",
        "Envoyer",
        "Recevoir",
        "Commerce",
        "Activité",
        "Tokens",
        "Réserve:",
        "Balance:",
        "Montant à envoyer:",
        "Entrez votre adresse de destination",
        "Entrez votre mémo (facultatif)",
        "Montant invalide",
        "Adresse invalide",
        "Solde disponible:",
        "Vous envoyez:",
        "Frais:",
        "Il y a une minute",
        "Il y a quelques minutes",
        "Il y a quelques secondes",
        "Ajouter",
        "Token Ajouté",
        "Token supprimé",
        "Votre paiement a réussi.",
        "Votre paiement a échoué.",
        "Vérifier l'adresse de destination",
        "et essayez à nouveau.",
        "Le reçu de transaction sera bientôt",
        "ajouté à la liste des activités.",
        "Partenaire",
        "Token à recevoir:",
        "Vous pouvez également recevoir ce token avec votre adresse XLM.",
        "Vous pouvez recevoir n'importe quel token avec votre adresse XLM.",
        "Tapez pour copier l'adresse",
        "Sélectionner un token",
        "Détails",
        "Diagramme",
        "Partager",
        "Site Web",
        "Supprimer le token",
        "Vérifié",
        "De confiance",
        "Solde non nul",
        "Paiement reçu",
        "Paiement envoyé",
        "Echanges",
        "Trustline",
        "Autre",
        "Déconnexion",
        "Gérer son compte",
        "Développé par: ",
        "Distribué par: ",
        "Licence: ",
        "Licences des dépendances",
        "Attention",
        "Les transactions comportent des risques importants et peuvent entraîner la perte de votre capital investi. Vous ne devez pas investir plus que ce que vous pouvez vous permettre de perdre et vous devez vous assurer de bien comprendre les risques encourus.",
        "Liens juridiques",
        "Conditions d'utilisation",
        "Politique de confidentialité",
        "Aide",
        "Soutien: ",
        "Sécurité: ",
        "Voir sur Github",
        "Le code source du projet est disponible sur Github.",
        "Votre portefeuille est vide",
        "Partagez votre addresse avec vos amis.",
        "Erreur de connexion. Nouvelle tentative ...",
        "Token autorisé",
        "Token refusé",
        "Options changées",
        "Données modifiées",
        "Séquence Bumped",
        "Compte fusionné",
        "Ordre de vente",
        "Annuler l'offre de vente",
        "Path Payment",
        "Compte Watch Only",
        "Pas de données disponibles.",
        "(24H)",
        "Les données du code QR ont été copiées dans le presse-papier.",
        "L'adresse a été copiée dans le presse-papier.",
        "Mémo Copié:",
        "Nom de domaine",
        "Attendez...",
        "Code:",
        "Emetteur du Token:",
        "Description:",
        "Conditions:",
        "Les lumens sont le token natif du réseau Stellar. Un lumen (XLM) est une unité de monnaie numérique, similaire au bitcoin.",
        "Le nombre de lumens créés lors de la genèse était de 100 milliards. Chaque année, il y a un taux d'inflation de 1%. Les nouveaux lumens ne peuvent être générés arbitrairement.",
        "Ajout désactivé. Pas assez de réserve XLM.",
        "Emetteur:",
        "Mon adresse:",
        "partage via",
        "Entrez une clé privée, une addresse publique ou",
        "votre phrase secrète pour importer le compte.",
        "Paramètres du compte",
        "Sauvez votre phrase secrète",
        "Renommez votre compte",
        "Supprimez votre compte",
        "Etes-vous sure? Confirmez.",
        "Etes-vous vraiment sure?",
        "Dernière chance! Confirmez.",
        "Suppression...",
        "Etrez un nouveau nom",
        "Quote Currency",
        "Importez un compte",
        "Entrez un compte valide",
        "IMPORTEZ UN COMPTE",
        "Importation: ",
        "Addresses Récentes",
        "Payment Reçu: ",
        "Notifications",
        "Toasts",
        "Obtenez une Friendly Address",
        "Commerce"
    ];

    /**
     * Language pack for Russian.
     * @member russianLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const russianLanguagePack = [
        "Создать новый PIN-код",
        "Введите Ваш PIN-код",
        "Подтвердите Ваш PIN-код",
        "Войти",
        "Далее",
        "Крипто-мир безграничен, изучайте его.",
        "Неверный PIN-код. Пожалуйста, попробуйте ещё.",
        "Ваш PIN-код должен быть от 4 до 12 цифр.",
        "Удостоверьтесь, что вы выбрали такой, который сложно угадать.",
        "Опции",
        "Переключить учётные записи", // 10
        "Создать учётную запись",
        "Импортировать учётную запись",
        "Выбрать язык",
        "Помощь & обратная связь",
        "Конфигурируем языковые настройки. Пожалуйста, подождите...",
        "Загрузка Вашей учётной записи. Пожалуйста, подождите...",
        "Учётная запись",
        "Загрузка Вашей учётной записи. Пожалуйста, подождите...",
        "СОХРАНИТЕ ВАШУ ФРАЗУ ДЛЯ ВОССТАНОВЛЕНИЯ",
        "Пожалуйста запишите эти 24 слова на бумаге.", // 20
        "Если Вы потеряете Ваш PIN-код или устройство",
        "эти слова позволяют Вам восстановить Ваши средства.",
        "Хорошо",
        "Запишите",
        "Проверьте",
        "Завершить",
        "Следующий шаг",
        "Закрыть",
        "Наберите Ваши слова в том же порядке (1-24).",
        "Используйте пробел чтобы разделять слова", //30
        "УСПЕШНО!",
        "НЕУДАЧА!",
        "Ваша фраза для восстановления не подтвердилась.",
        "Ваша учётная запись не имеет резервной копии.",
        "Убедитесь что Вы записываете все слова с 1 по 24.",
        "Храните Вашу фразу для восстановления в секрете!",
        "Используйте эти 24 слова чтобы восстановить Ваши средства",
        "в случае потери или забытого PIN-кода.",
        "Сделано с любовью",
        "Баланс", // 40
        "Загрузка...",
        "Проверено",
        "Не проверено",
        "Послать",
        "Получить",
        "Торговля",
        "Активность",
        "Активы",
        "Резерв:",
        "Баланс:", // 50
        "Сумма для отправки:",
        "Введите Ваш адрес назначения",
        "Введите Ваш memo (не обязательно)",
        "Неверная сумма",
        "Неверный адрес",
        "Доступный баланс:",
        "Вы посылаете:",
        "Комиссия:",
        "минуту назад",
        "минуты назад", // 60
        "Несколько секунд назад",
        "Добавить",
        "Актив добавлен",
        "Актив удалён",
        "Ваш платёж проведён успешно.",
        "Ваш платёж не проведён.",
        "Проверьте адрес получения",
        "и попробуйте снова.",
        "Квитанция о транзакции будет вскоре",
        "добавлена в Список Активности.", // 70
        "Партнёр",
        "Актив для получения:",
        "Также Вы можете получить этот актив используя Ваш XLM адрес.",
        "Вы можете получить любой актив используя Ваш XLM адрес.",
        "Нажмите чтобы скопировать адрес",
        "Выберите актив",
        "Детали",
        "График цен",
        "Поделиться",
        "веб-сайт", // 80
        "Удалить актив",
        "Проверено",
        "Доверенный",
        "Ненулевой баланс",
        "Получение оплаты",
        "Отправление оплаты",
        "Сделки",
        "Доверительные связи",
        "Другое",
        "Выход", // 90
        "Управление учётной записью",
        "Разработано: ",
        "Распространяется: ",
        "Лицензия: ",
        "Лицензионные зависимости",
        "Внимание",
        "Торговля сопряжена со значительным риском и может привести к потере Вашего инвестированного капитала. Не нужно  инвестировать больше, чем Вы можете позволить себе потерять, а также Вы должны быть уверены что полностью понимаете связанные с ней риски.",
        "Легальные ссылки",
        "Условия использования",
        "Политика конфиденциальности", //100
        "Помощь",
        "Поддержка: ",
        "Безопасность: ",
        "Посмотреть на Github",
        "Исходные тексты этого проекта доступны на Github.",
        "Ваш кошелёк пустой,",
        "Время надоесть Вашим друзьям.",
        "Ошибка соединения. Повтор...",
        "Актив разрешён",
        "Актив запрещён", // 110
        "Опции изменены",
        "Данные изменены",
        "Изменение последовательности",
        "Учётная запись объединена",
        "Ордер на продажу",
        "Отменить ордер на продажу",
        "Путь оплаты",
        "Учётная запись только для просмотра",
        "Данные не доступны.",
        "(24ч.)", // 120
        "Данные QR-кода скопированы в буфер обмена.",
        "Адрес скопирован в буфер обмена.",
        "Memo скопировано:",
        "Введите название домена-эмитента",
        "Подождите...",
        "Код:",
        "Эмитент актива:",
        "Описание:",
        "Условия:",
        "Люмены это собственный актив сети Stellar. Один люмен (XLM) это единица цифровой валюты, как и биткоин.", // 130
        "Количество люменов определяется фиксированными правилами на уровне протокола. Изначально созданное количество люменов было 100 миллиардов. Каждый год добавляет 1% инфляции. Новые люмены не могут генерироваться произвольно кем-либо.",
        "Добавление отключено. Недостаточный XLM резерв.",
        "Эмитент:",
        "Мой адрес:",
        "Поделиться через",
        "Введите приватный ключ, публичный адрес или",
        "24-словную фразу для восстановления чтобы импортировать учётную запись.",
        "Настройки учётной записи",
        "Сохранить Вашу фразу для восстановления",
        "Переименовать учётную запись", // 140
        "Удалить учётную запись",
        "Вы уверены? Нажмите для подтверждения.",
        "Вы на самом деле уверены?",
        "Последний шанс! Нажмите чтобы удалить учётную запись.",
        "Удаление...",
        "Введите название новой учётной записи",
        "Котируемая валюта",
        "Импорт учётной записи",
        "Введите действительную учётную запись",
        "ИМПОРТ УЧЁТНОЙ ЗАПИСИ",//150
        "Импортирование: ",
        "Последние адреса",
        "Оплата получена: ",
        "Уведомления",
        "Всплывающие сообщения",
        "Получить Ваш дружеский адрес",
        "Рынок"
    ];

    /**
     * Language pack for Korean.
     * @member koreanLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const koreanLanguagePack = [
        "PIN 만들기",
        "PIN 입력",
        "PIN 확인",
        "로그인",
        "다음",
        "새로운 크립토월드를 경험하세요.",
        "PIN이 잘못되었습니다. 다시 시도하십시오.",
        "귀하의 PIN은 4-12 자입니다.",
        "추측하기 어려운 것을 선택하십시오.",
        "옵션",
        "계정 전환", // 10
        "계정 만들기",
        '계정 가져 오기',
        "언어 선택",
        "도움말 및 피드백",
        "잠시만 기다려주십시오.",
        "귀하의 계정을 로드 중입니다. 잠시만 기다려주십시오.",
        "계정",
        "귀하의 계정을 로드 중입니다. 잠시만 기다려주십시오.",
        "백업 단어를 저장하십시오",
        "24개의 단어를 종이에 적어주세요.", // 20
        "PIN 또는 기기를 분실 한 경우",
        "24개의 단어로 당신의 코인을 되 찾을 수 있습니다.",
        "승인",
        "스탭1",
        "스탭2",
        "완료",
        "다음 단계",
        "닫기",
        "같은 순서로 단어를 입력하십시오 (1-24).",
        "각 단어를 구분하는 데 공백을 사용하십시오", // 30
        "성공!",
        "실패!",
        "귀하의 백업 구문이 검증되지 않았습니다.",
        "귀하의 계정은 백업되지 않았습니다.",
        "1에서 24까지 모든 단어를 입력하세요.",
        "백업 구문 보안에 유의하세요!",
        "이 24 단어를 사용하여 코인을 회수하십시오.",
        "PIN또는 기기를 분실 한 경우 백업 단어를 사용하세요.",
        "Made with Love",
        "계정의 잔액", // 40
        "로딩 중 ...",
        "확인",
        "확인되지 않음",
        "센드",
        "리시브",
        "트레이드",
        "활동 로그",
        "토큰",
        "Reserve:",
        "계정의 잔액:", // 50
        "보내실 금액 :",
        "받으실 곳 주소 입력",
        "메모 입력 (선택)",
        "유효하지 않은 금액",
        "잘못된 주소",
        "사용 가능한 잔액:",
        "Sending:",
        "수수료:",
        "분 전",
        "분 전", // 60
        "몇 초 전",
        "추가",
        "추가되었습니다.",
        "삭제되었습니다.",
        "결제가 완료되었습니다.",
        "결제가 처리되지 않았습니다.",
        "주소를 한번 더 확인하세요.",
        "다시 시도하십시오.",
        "거래 영수증이 곧 제공될 것입니다.",
        "활동 목록에 추가하십시오.", // 70
        "파트너",
        "토큰 :",
        "또한 XLM 주소로 토큰을 받으실 수 있습니다.",
        "XLM 주소로 모든 종류의 토큰을 받으실 수 있습니다.",
        '주소를 복사하려면 누르십시오',
        "토큰 선택",
        "세부사항",
        "시세표",
        "공유하기",
        "웹사이트", // 80
        "토큰 삭제",
        '확인 됨',
        "신뢰할 수 있는 토큰",
        "잔액 > 0",
        "Payment Received",
        "Payment Sent",
        "Trades",
        "Trustlines",
        "다른",
        "로그아웃", // 90
        "계정관리",
        "개발자 :",
        "배포자 :",
        "라이센스 :",
        "종속성 라이선스",
        "경고",
        "거래에는 중대한 위험이 따르며 투자 자본 손실을 초래할 수 있습니다. 잃을 수 있는 것 이상 투자해서는 안되며 관련된 위험을 완전히 이해해야 합니다.",
        "법적 링크",
        "사용 기간",
        "개인 정보 보호 정책", // 100
        "도움말",
        "Support: ",
        "보안 :",
        "Github에서 보기",
        "이 프로젝트 소스 코드는 Github에서 확인할 수 있습니다.",
        "지갑이 비어 있습니다.",
        "지금 코인을 받아보세요.",
        "연결 오류. 다시 시도 중 ...",
        '토큰 허용됨',
        '허용되지 않는 토큰', // 110
        "옵션 변경됨",
        '데이터 변경됨',
        "Sequence Bumped",
        "계정합치기",
        "Sell Order",
        "Cancel Sell Order",
        "Path Payment",
        'Watch Only',
        "데이타 없음",
        "(24H)", // 120
        "QR 코드 데이터가 클립 보드로 복사되었습니다.",
        "주소가 클립 보드에 복사되었습니다.",
        "메모 복사 됨 :",
        "도메인 이름을 입력하세요.",
        "기다리세요",
        "토큰:",
        "발행계정:",
        "기술:",
        "컨디션:",
        "루멘는 스텔라 네트워크의 기본 자산이며 하나의 루멘(XLM)은 비트 코인과 같은 디지털 통화 단위입니다.", // 130
        "루멘 공급은 고정 된 프로토콜 수준의 규칙에 의해 결정되며 기원에서 생성 된 루멘 수는 1, 000억 개이며 매년 1 % 의 인플레이션 율이 있으며 새로운 루멘은 임의로 생성 할 수 없습니다.",
        "코인이 충분하지 않습니다.",
        "발행계정:",
        "내 주소:",
        "공유:",
        "프라이빗 키 또는 공용 주소 또는",
        "24개의 백업 단어를 입력하십시오",
        "계정 설정",
        "백업 단어 저장",
        "계정 이름 변경", // 140
        "계정 삭제",
        "확실합니까? 확인하려면 누르십시오.",
        "다시한번 생각해 보세요",
        "마지막 기회! 탭하여 계정을 삭제하십시오.",
        "계정 삭제 중 ...",
        "새 계정 이름 입력",
        "Quote Currency",
        "계정 가져 오기",
        "유효한 계정을 입력하십시오.",
        "계정 가져 오기", // 150
        "계정: ",
        "최근 사용한 내역",
        "입금된 금액: ",
        "알림",
        "Toasts",
        "나만의 주소를 만들어보세요.",
        "마켓플레이스"
    ];

    "Import Account",
        "Enter a valid account",
        "IMPORT AN ACCOUNT",//150
        "Importing: ",
        "Recent Addresses",
        "Payment Received: ",
        "Notifications",
        "Toasts",
        "Get Your Friendly Address",
        "Marketplace"


    /**
     * List of language packs.
     * @member languagePacks
     * @memberof Litemint.Pepper.Resources
    */
    namespace.Pepper.Resources.languagePacks = {
        "en": { "name": "English", "text": englishLanguagePack },
        "fr": { "name": "Français", "text": frenchLanguagePack },
        "de": { "name": "Deutsch", "text": germanLanguagePack },
        "ru": { "name": "Русский", "text": russianLanguagePack, "scale": 0.95 },
        "kr": { "name": "한국어", "text": koreanLanguagePack }
    };

    /**
     * Default language.
     * @member defaultLanguage
     * @memberof Litemint.Pepper.Resources
    */
    namespace.Pepper.Resources.defaultLanguage = "en";

})(window.Litemint = window.Litemint || {});
