/**
 * @overview Litemint Pepper resources languages implementation.
 * @copyright 2018-2020 Frederic Rezeau, aka 오경진.
 * @copyright 2018-2020 Litemint LLC.
 * @license [MIT]{@link https://github.com/litemint/litemint/blob/master/LICENSE}
 */

(function (namespace) {
    "use strict";

    /**
     * Language pack for English.
     * @member englishLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const englishLanguagePack = [
        "Create New PIN",
        "Enter your PIN",
        "Confirm your PIN",
        "Sign In",
        "Next",
        "Explore the crypto world.",
        "Incorrect PIN. Please try again.",
        "Your PIN can be 4-12 digits.",
        "Make sure you choose one that's hard to guess.",
        "Options",
        "Switch accounts", // 10
        "Create account",
        "Import account",
        "Select language",
        "Help & feedback",
        "Configuring language. Please wait...",
        "Loading your account. Please wait...",
        "Account",
        "Loading your account. Please wait...",
        "SAVE YOUR BACKUP PHRASE",
        "Please write down these 24 words on a paper.", // 20
        "If you lose your PIN or device",
        "these words allow you to restore your funds.",
        "OK",
        "Write",
        "Verify",
        "Finish",
        "Next Step",
        "Close",
        "Type your words in the same order (1-24).",
        "Use a space to separate each word", //30
        "SUCCESS!",
        "FAILED!",
        "Your backup phrase was not validated.",
        "Your account is not backed-up.",
        "Make sure you write all words from 1 to 24.",
        "Keep your backup phrase secret!",
        "Use these 24 words to recover your funds",
        "in case of loss or forgotten PIN.",
        "Made with love",
        "Balance", // 40
        "Loading...",
        "Verified",
        "Unverified",
        "Send",
        "Receive",
        "Trade",
        "Activity",
        "Assets",
        "Reserve:",
        "Balance:", // 50
        "Amount to send:",
        "Enter your destination address",
        "Enter your memo (optional)",
        "Invalid Amount",
        "Invalid Address",
        "Available balance:",
        "You are sending:",
        "Fee:",
        "minute ago",
        "minutes ago", // 60
        "Few seconds ago",
        "Add",
        "Asset Added",
        "Asset Removed",
        "Your payment was successful.",
        "Your payment was not successful.",
        "Verify the destination address",
        "and try again.",
        "The transaction receipt will shortly",
        "be added to the Activity List.", // 70
        "Partner",
        "Asset to receive:",
        "You can also receive this asset with your XLM address.",
        "You can receive any asset with your XLM address.",
        "Tap to copy address",
        "Select Asset",
        "Details",
        "Price Chart",
        "Share",
        "Website", // 80
        "Remove Asset",
        "Verified",
        "Trusted",
        "Non-zero Balance",
        "Payment Received",
        "Payment Sent",
        "Trades",
        "Trustlines",
        "Other",
        "Sign Out", // 90
        "Manage Account",
        "Developed by: ",
        "Distributed by: ",
        "License: ",
        "Dependency Licenses",
        "Warning",
        "Trading involves significant risk and can result in the loss of your invested capital. You should not invest more than you can afford to lose and should ensure that you fully understand the risks involved.",
        "Legal Links",
        "Term of Use",
        "Privacy Policy", //100
        "Help",
        "Support: ",
        "Security: ",
        "View on Github",
        "This project source code is available on Github.",
        "Your wallet is empty,",
        "use your receive address.",
        "Connection error. Retrying...",
        "Asset Allowed",
        "Asset Disallowed", // 110
        "Options Changed",
        "Data Changed",
        "Sequence Bumped",
        "Account Merged",
        "Sell Order",
        "Cancel Order",
        "Path Payment",
        "Watch Only Account",
        "No Data Available.",
        "(24H)", // 120
        "The QR code data was copied to clipboard.",
        "The address was copied to clipboard.",
        "Memo Copied:",
        "Enter issuer domain name",
        "Wait...",
        "Code:",
        "Asset Issuer:",
        "Description:",
        "Conditions:",
        "Lumens are the native asset of the Stellar network. One lumen (XLM) is a unit of digital currency, like a bitcoin.", // 130
        "Lumen supply is determined by fixed, protocol-level rules. Currently, the total supply of lumens is 50 billion. New lumens cannot be generated arbitrarily by anyone.",
        "Adding disabled. Not enough XLM reserve.",
        "Issuer:",
        "My Address:",
        "Share via",
        "Enter a private key, public address or",
        "24-word backup phrase to import an account.",
        "Account Settings",
        "Save your backup phrase",
        "Rename Account", // 140
        "Delete Account",
        "Are you sure? Tap to confirm.",
        "Are you really sure?",
        "Last chance! Tap to delete account.",
        "Deleting...",
        "Enter new account name",
        "Quote Currency",
        "Import Account",
        "Enter a valid account",
        "IMPORT AN ACCOUNT",//150
        "Importing: ",
        "Recent Addresses",
        "Payment Received: ",
        "Notifications",
        "Toasts",
        "Get Your Friendly Name",
        "Marketplace",
        "Give Us Some Love",
        "Help us grow and rate us if you enjoy Litemint!",
        "Not Supported Yet!", // 160
        "Buy",
        "Sell",
        "Trade",
        "The order book is empty.",
        "Price",
        "Amount",
        "Last Trades",
        "Add Asset",
        "Select Asset",
        "Orders", // 170
        "Offer",
        "Cancel Offer",
        "Cancelling...",
        "Confirm?",
        "Place Order",
        "Total:",
        "Submitting your order, please wait...",
        "The transaction failed.",
        "Your order was submitted successfully.",
        "Games", // 180
        "GAMES",
        "COLLECTIBLES",
        "SHOP",
        "Coming Soon",
        "Leaderboard",
        "Playing as 'Guest'. Get your Gamer ID!",
        "Players:",
        "Refreshing prices...",
        "Price Not available",
        "Terms", // 190
        "Privacy",
        "Refresh Prices",
        "Prices are calculated from Stellar DEX current best offers.",
        "Seller Website",
        "Finding best price...",
        "Please wait...",
        "Buy Now",
        "Price",
        "Checkout",
        "Shopping", // 200
        "Thank you for your payment!",
        "Processing...",
        "Explore",
        "APPS",
        "Choose your PIN.",
        "Confirm it.",
        "Done.",
        "Can be traded (DEX)",
        "Quick deposit with CoinSwitch",
        "Select Deposit Amount", // 210
        "Select Deposit Currency",
        "More...",
        "You receive:",
        "CONTINUE",
        "Quick Deposit",
        "Fund Your Account to Buy",
        "Verifying NFT contract...",
        "Owner",
        "Not Owner",
        "Daily", // 220
        "All Time",
        "ATH",
        "Donate",
        "Donate",
        "Donate Now",
        "No Winner",
        "Buy Order"
    ];

    /**
     * Language pack for German.
     * @member germanLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const germanLanguagePack = [
        "Neue PIN erzeugen",
        "PIN eingeben",
        "PIN bestätigen",
        "Einloggen",
        "Weiter",
        "Krypto ist grenzenlos, erforsche es.",
        "Falsche PIN. Nochmal versuchen.",
        "Die PIN kann zw. 4-12 Zahlen lang sein.",
        "Wähle eine PIN, welche schwer zu erraten ist.",
        "Optionen",
        "Konto wechseln", // 10
        "Konto erzeugen",
        "Konto importieren",
        "Sprache wählen",
        "Hilfe & Rückmeldung",
        "Konfiguriere Sprache, bitte warten...",
        "Konto wird geladen, bitte warten...",
        "Konto",
        "Konto wird geladen, bitte warten...",
        "SICHERE DEINE WIEDERHERSTELLUNGS-PHRASE",
        "Schreibe die nächsten 24 Wörter auf Papier.", // 20
        "Falls du dein Gerät oder die PIN verlierst",
        "können diese Wörter dein Konto wiederherstellen.",
        "OK",
        "Schreibe",
        "Verifiziere",
        "Beende",
        "Nächster Schritt",
        "Schließen",
        "Tippe die Wörter in gleicher Reihenfolge (1-24).",
        "Benutze ein Leerzeichen zw. den Wörtern", //30
        "ERFOLGREICH!",
        "FEHLGESCHLAGEN!",
        "Wiederherstellungs-Phrase nicht bestätigt.",
        "Dein Konto ist nicht gesichert.",
        "Schreibe alle Wörter von 1-24.",
        "Halte deine Wiederherstellungs-Phrase geheim!",
        "Benutze die 24 Wörter um dein Konto wiederherzustellen.",
        "falls du dein Gerät oder die PIN verlierst.",
        "Mit Liebe gemacht",
        "Guthaben", // 40
        "Lade...",
        "Verifiziert",
        "Nicht verifiziert",
        "Senden",
        "Empfangen",
        "Tauschen",
        "Aktivitäten",
        "Währungen",
        "Reserve:",
        "Guthaben:", // 50
        "Betrag zu senden:",
        "Empfangsadresse eingeben",
        "Notiz einfügen (optional)",
        "Ungültiger Betrag",
        "Ungültige Adresse",
        "Verfügbares Guthaben",
        "Sie senden:",
        "Gebühr:",
        "Minute",
        "Minuten", // 60
        "vor ein paar Sekunden",
        "Hinzufügen",
        "Währung hinzugefügt",
        "Währung entfernt",
        "Deine Zahlung war erfolgreich.",
        "Deine Zahlung ist fehlgeschlagen.",
        "Überprüfen die Empfangsadresse",
        "und versuche es nochmal.",
        "Der Transaktionsempfang wird bald",
        "in deiner Aktivitätenliste aufscheinen.", // 70
        "Partner",
        "Empfangswährung:",
        "Sie können diese Währung mit der XML Adressee empfangen.",
        "Sie können jegliche Währung mit der XML Adressee empfangen.",
        "Berühren, um Adresse zu kopieren",
        "Währung wählen",
        "Details",
        "Preisdiagramm",
        "Teilen",
        "Webseite", // 80
        "Währung entfernen",
        "Verifiziert",
        "Vertrauenswürdig",
        "Leere Guthaben ausblenden",
        "Zahlung empfangen",
        "Zahlung gesendet",
        "Handel",
        "Vertrauenslinien",
        "Andere",
        "Ausloggen", // 90
        "Konto verwalten",
        "Entwickelt von: ",
        "Verteilt von: ",
        "Lizenz: ",
        "Abhängigkeitslizenzen",
        "Warnung",
        "Der Handel ist mit erheblichen Risiken verbunden und kann zum Verlust Ihres investierten Kapitals führen. Sie sollten nicht mehr investieren, als Sie sich leisten können, und sicherstellen, dass Sie die damit verbundenen Risiken vollständig verstehen.",
        "Rechtliche Links",
        "Nutzungsbedinungen",
        "Datenschutzbestimmungen", //100
        "Hilfe",
        "Support: ",
        "Sicherheit: ",
        "Auf Github anzeigen",
        "Der Quellcode dieses Projektes ist auf Github einsehbar.",
        "Deine Geldbörse ist leer,",
        "Es wird Zeit, deine Freunde anzupumpen.",
        "Verbindungsfehler, wiederhole... ",
        "Währung erlaubt",
        "Währung verboten", // 110
        "Optionen geändert",
        "Daten geändert",
        "Sequenz angestoßen",
        "Konten zusammengeführt",
        "Verkaufsauftrag",
        "Verkauf abgebrochen",
        "Pfadzahlung",
        "Beobachtungskonto",
        "Keine Daten verfügbar",
        "(24H)", // 120
        "Der QR code wurde in die Zwischenablage kopiert.",
        "Die Adresse wurde in die Zwischenablage kopiert.",
        "Notiz kopiert:",
        "Ausstellers Domainname eingeben",
        "Warte...",
        "Code:",
        "Herausgeber:", //previous: "Ausstellers Währung"
        "Beschreibung:",
        "Konditionen:",
        "Lumen sind die eigentliche Währung des Stellar Netzwerkes. Ein Lumen (XML) ist eine Einheit dieser digitalen Währung, so wie Bitcoin.", // 130
        "Anzahl der Lumen ist durch feste Regeln auf Protokollebene bestimmt. Die Anzahl bei der Entstehung erzeugten Lumen betrug 100 Milliarden. Neue Lumen können von niemandem beliebig generiert werden.",
        "Hinzufügen deaktiviert. Nicht genügend XML.",
        "Aussteller:",
        "Ihre Adresse:",
        "Teilen mit",
        "Einen Privaten Schlüssel, Öffentliche Adresse oder die",
        "24 Wörter der Wiederherstellungs-Phrase eingeben um ein Konto zu importieren.",
        "Kontoeinstellungen",
        "Sichern Sie ihre Wiederherstellungs-Phrase",
        "Konto umbenennen", // 140
        "Konto löschen",
        "Sind Sie sicher? Zur Bestätigung berühren.",
        "Sind Sie sich wirklich sicher?",
        "Letzte Chance! Hier berühren um zu bestätigen.",
        "Lösche...",
        "Neuen Kontonamen eingeben",
        "Währung wählen",
        "Konto importieren",
        "Gültiges Konto eingeben",
        "KONTO IMPORTIEREN",//150
        "Importiere: ",
        "Letzte Adressen",
        "Zahlung erhalten: ",
        "Benachrichtigungen",
        "Toasts",
        "Ihre einfache Adresse bekommen",
        "Marktplatz",
        "Gib uns etwas Liebe",
        "Hilf uns zu wachsen, bewerte Litemint!",
        "Noch nicht unterstützt!", // 160
        "Kaufen",
        "Verkaufen",
        "Tauschen",
        "Auftragsbuch ist leer.",
        "Preis",
        "Menge",
        "Letzte Trades",
        "Währung hinzufügen",
        "Wähle Währung",
        "Aufträge", // 170
        "Angebot",
        "Angebot stornieren",
        "Stornieren...",
        "Bestätigen?",
        "Angebot platzieren",
        "Total:",
        "Auftrag wird gesendet, bitte warten...",
        "Transaktion ist fehlgeschlagen.",
        "Ihr Auftrag wurde erfolgreich abgeschickt.",
        "Spiele", // 180
        "SPIELE",
        "SAMMLUNG",
        "SHOP",
        "Demnächst",
        "Bestenliste",
        "Als Gast spielen. Hol dir deine Gamer ID!",
        "Spieler:",
        "Aktualisiere Preis...",
        "Preis nicht verfügbar",
        "AGB", // 190
        "Datenschutz",
        "Aktualisiere Preis",
        "Preis wird über Stellar DEX bestes Angebot berechnet.",
        "Verkäufer Website",
        "Suche den besten Preis...",
        "Bitte warten...",
        "Kaufen",
        "Preis",
        "Kasse",
        "Einkaufen", // 200
        "Danke für Ihre Zahlung!",
        "In Bearbeitung...",
        "Erkunden",
        "APPS",
        "Wähle deinen PIN.",
        "Bestätigen.",
        "Fertig.",
        "Kann gehandelt werden (DEX)",
        "Einzahlen mit CoinSwitch",
        "Wähle Einzahlungsbetrag", // 210
        "Wähle Einzahlungswährung",
        "Mehr...",
        "Du erhälst:",
        "WEITER",
        "Einzahlen",
        "Aufs Konto einzahlen um einzukaufen",
        "Verifiziere NFT Vetrag...",
        "Inhaber",
        "Nicht Inhaber",
        "Täglich", // 220
        "Allzeit",
        "ATH"                
    ];

    /**
     * Language pack for French.
     * @member frenchLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const frenchLanguagePack = [
        "Créer un nouveau code PIN",
        "Entrez votre code PIN",
        "Confirmez votre code PIN",
        "Se connecter",
        "Suivant",
        "Explorez le monde des cryptos.",
        "Code PIN incorrect. Veuillez réessayer.",
        "Votre code PIN peut être composé de 4 à 12 chiffres.",
        "Assurez-vous d'en choisir un difficile à deviner.",
        "Options",
        "Changer de compte",
        "Créer un compte",
        "Importer un compte",
        "Choisir la langue",
        "Aide et commentaires",
        "Configuration de la langue. Veuillez patienter ...",
        "Chargement de votre compte. Veuillez patienter ...",
        "Compte",
        "Chargement de votre compte. Veuillez patienter ...",
        "SAUVEZ VOTRE PHRASE SECRETE",
        "S'il vous plaît écrivez ces 24 mots sur un papier.",
        "Si vous perdez votre code PIN ou votre appareil",
        "Ces mots vous permettent de restaurer vos fonds.",
        "OK",
        "Écrire",
        "Vérifier",
        "Terminer",
        "Etape suivante",
        "Fermer",
        "Tapez vos mots dans le même ordre (1-24).",
        "Utilisez un espace pour séparer chaque mot",
        "SUCCÈS!",
        "ÉCHEC!",
        "Votre phrase de sauvegarde n'a pas été validée.",
        "Votre compte n'est pas sauvegardé.",
        "Assurez-vous d'écrire tous les mots de 1 à 24.",
        "Gardez votre phrase de sauvegarde secrète!",
        "Utilisez ces 24 mots pour récupérer vos fonds",
        "en cas de perte ou de code PIN oublié.",
        "Fait avec Amour",
        "Balance",
        "Chargement...",
        "Vérifié",
        "Non vérifié",
        "Envoyer",
        "Recevoir",
        "Echanger",
        "Activité",
        "Tokens",
        "Réserve:",
        "Solde:",
        "Montant à envoyer:",
        "Entrez votre adresse de destination",
        "Entrez votre mémo (facultatif)",
        "Montant invalide",
        "Adresse invalide",
        "Solde disponible:",
        "Vous envoyez:",
        "Frais:",
        "minute",
        "minutes",
        "quelques secondes",
        "Ajouter",
        "Token Ajouté",
        "Token supprimé",
        "Votre paiement a réussi.",
        "Votre paiement a échoué.",
        "Vérifier l'adresse de destination",
        "et essayez à nouveau.",
        "Le reçu de transaction sera bientôt",
        "ajouté à la liste des activités.",
        "Partenaire",
        "Token à recevoir:",
        "Vous pouvez également recevoir ce token avec votre adresse XLM.",
        "Vous pouvez recevoir n'importe quel token avec votre adresse XLM.",
        "Tapez pour copier l'adresse",
        "Sélectionner un token",
        "Détails",
        "Graphique",
        "Partager",
        "Site Web",
        "Supprimer le token",
        "Vérifié",
        "De confiance",
        "Solde non nul",
        "Paiement reçu",
        "Paiement envoyé",
        "Echanges",
        "Trustline",
        "Autre",
        "Déconnexion",
        "Gérer son compte",
        "Développé par: ",
        "Distribué par: ",
        "Licence: ",
        "Licences des dépendances",
        "Attention",
        "Les transactions comportent des risques importants et peuvent entraîner la perte de votre capital investi. Vous ne devez pas investir plus que ce que vous pouvez vous permettre de perdre et vous devez vous assurer de bien comprendre les risques encourus.",
        "Liens juridiques",
        "Conditions d'utilisation",
        "Politique de confidentialité",
        "Aide",
        "Support: ",
        "Sécurité: ",
        "Voir sur Github",
        "Le code source du projet est disponible sur Github.",
        "Votre portefeuille est vide",
        "Partagez votre addresse avec vos amis.",
        "Erreur de connexion. Nouvelle tentative ...",
        "Token autorisé",
        "Token refusé",
        "Options modifiées",
        "Données modifiées",
        "Séquence Incrémentée",
        "Compte fusionné",
        "Ordre de vente",
        "Annuler l'offre de vente",
        "Chemin de Paiement",
        "Compte en Visionnage simple",
        "Pas de données disponibles.",
        "(24H)",
        "Les données du code QR ont été copiées dans le presse-papier.",
        "L'adresse a été copiée dans le presse-papier.",
        "Mémo Copié:",
        "Nom de domaine",
        "Attendez...",
        "Code:",
        "Emetteur du Token:",
        "Description:",
        "Conditions:",
        "Les lumens sont le token natif du réseau Stellar. Un lumen (XLM) est une unité de monnaie numérique, similaire au bitcoin.",
        "Le nombre de lumens créés lors de la genèse était de 100 milliards. Les nouveaux lumens ne peuvent être générés arbitrairement.",
        "Ajout désactivé. Pas assez de réserve XLM.",
        "Emetteur:",
        "Mon adresse:",
        "partage via",
        "Entrez une clé privée, une addresse publique ou",
        "votre phrase secrète pour importer le compte.",
        "Paramètres du compte",
        "Sauvez votre phrase secrète",
        "Renommez votre compte",
        "Supprimez votre compte",
        "Etes-vous sûr? Confirmez.",
        "Etes-vous vraiment sûr?",
        "Dernière chance! Confirmez.",
        "Suppression...",
        "Entrez un nouveau nom",
        "Devise de cotation",
        "Importez un compte",
        "Entrez un compte valide",
        "IMPORTEZ UN COMPTE",
        "Importation: ",
        "Addresses Récentes",
        "Paiement Reçu: ",
        "Notifications",
        "Toasts",
        "Obtenez une Addresse Simplifiée",
        "Commerce",
        "Coup de coeur?",
        "Si vous aimez Litemint, aidez-nous à grandir et faites passer le message.",
        "Pas encore supporté!", // 160
        "Acheter",
        "Vendre",
        "Echanger",
        "Le carnets d'ordres est vide.",
        "Prix",
        "Montant",
        "Dernières Transactions",
        "Ajouter Token",
        "Sélectionner Token",
        "Ordres", // 170
        "Offres",
        "Annuler Offre",
        "Annulation...",
        "Confirmer?",
        "Placer Ordre",
        "Total:",
        "Votre ordre est en cours, patientez...",
        "La transaction a échoué.",
        "Votre ordre a été soumis.",
        "Jeux", // 180
        "JEUX",
        "COLLECTIONS",
        "SHOP",
        "Bientôt disponible",
        "Classement",
        "Vous jouez en 'Invité'. Obtenez un Gamer ID!",
        "Joueurs:",
        "Mise à jour des prix...",
        "Non disponible dans cette devise.",
        "Termes", // 190
        "Vie privée",
        "Mise à jour des prix",
        "Les prix sont calculés selon les meilleures offres sur le Stellar DEX.",
        "Site du vendeur",
        "Recherche du meilleur prix...",
        "Veuillez Patienter...",
        "Acheter Maintenant",
        "Prix",
        "Checkout",
        "Achats", // 200
        "Merci pour votre paiement!",
        "En cours...",
        "Explore",
        "APPS",
        "Choisissez un code PIN.",
        "Confirmez-le.",
        "Prêt.",
        "Peut être échangé (DEX)",
        "Dépôt Rapide avec CoinSwitch",
        "Sélectionner un montant", // 210
        "Sélectionner un token",
        "Plus...",
        "Vous recevez:",
        "CONTINUER",
        "Dépôt Rapide",
        "Ajoutez des fonds pour achetez",
        "Vérification du contrat NFT...",
        "Propriétaire",
        "Non Propriétaire"
    ];

    /**
     * Language pack for Russian.
     * @member russianLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const russianLanguagePack = [
        "Создать новый PIN",
        "Введите Ваш PIN",
        "Подтвердите Ваш PIN",
        "Войти",
        "Далее",
        "КриптоМир безграничен, изучайте его.",
        "Неверный PIN. Пожалуйста, попробуйте ещё.",
        "Ваш PIN может быть 4-12 цифр.",
        "Удостоверьтесь, что выбрали тот, который сложно угадать.",
        "Опции",
        "Переключить учётные записи", // 10
        "Создать учётную запись",
        "Импортировать учётную запись",
        "Выбрать язык",
        "Помощь & обратная связь",
        "Настраиваем язык. Пожалуйста, подождите...",
        "Загрузка Вашей учётной записи. Пожалуйста, подождите...",
        "Учётная запись",
        "Загрузка Вашей учётной записи. Пожалуйста, подождите...",
        "СОХРАНИТЕ ВАШУ ФРАЗУ ВОССТАНОВЛЕНИЯ",
        "Пожалуйста запишите эти 24 слова на бумаге.", // 20
        "Если Вы потеряете Ваш PIN или устройство",
        "эти слова позволяют Вам восстановить Ваши средства.",
        "Хорошо",
        "Запишите",
        "Проверьте",
        "Завершить",
        "Следующий шаг",
        "Закрыть",
        "Наберите Ваши слова в том же порядке (1-24).",
        "Используйте пробел чтобы разделять слова", //30
        "УСПЕШНО!",
        "НЕУДАЧА!",
        "Ваша фраза восстановления не подтвердилась.",
        "Ваша учётная запись не имеет резервной копии.",
        "Убедитесь что Вы записываете все слова с 1 по 24.",
        "Храните Вашу фразу восстановления в секрете!",
        "Используйте эти 24 слова для восстановления Ваших средств",
        "в случае потерянного или забытого PIN.",
        "Сделано с любовью",
        "Баланс", // 40
        "Загрузка...",
        "Проверено",
        "Не проверено",
        "Послать",
        "Получить",
        "Торговля",
        "Активность",
        "Активы",
        "Резерв:",
        "Баланс:", // 50
        "Сумма для отправки:",
        "Введите Ваш адрес назначения",
        "Введите Ваш memo (не обязательно)",
        "Неверная сумма",
        "Неверный адрес",
        "Доступный баланс:",
        "Вы посылаете:",
        "Комиссия:",
        "минуту назад",
        "минут назад", // 60
        "Несколько секунд назад",
        "Добавить",
        "Актив добавлен",
        "Актив удалён",
        "Ваш платёж проведён успешно.",
        "Ваш платёж не проведён.",
        "Проверьте адрес получения",
        "и попробуйте снова.",
        "Квитанция о транзакции будет вскоре",
        "добавлена в Список Активности.", // 70
        "Партнёр",
        "Актив для получения:",
        "Также Вы можете получить этот актив на Ваш XLM адрес.",
        "Вы можете получить любой актив на Ваш XLM адрес.",
        "Нажмите для копирования адреса",
        "Выберите актив",
        "Детали",
        "График цен",
        "Поделиться",
        "веб-сайт", // 80
        "Удалить актив",
        "Проверено",
        "Доверенный",
        "Ненулевой баланс",
        "Оплата получена",
        "Оплата отправлена",
        "Сделки",
        "Доверительные связи",
        "Другое",
        "Выход", // 90
        "Управление учётной записью",
        "Разработано: ",
        "Распространяется: ",
        "Лицензия: ",
        "Лицензионные зависимости",
        "Внимание",
        "Торговля сопряжена со значительным риском и может привести к потере Вашего инвестированного капитала. Не нужно  инвестировать больше, чем Вы можете позволить себе потерять, а также Вы должны быть уверены что полностью понимаете связанные с ней риски.",
        "Легальные ссылки",
        "Условия использования",
        "Политика конфиденциальности", //100
        "Помощь",
        "Поддержка: ",
        "Безопасность: ",
        "Посмотреть на Github",
        "Исходные тексты этого проекта доступны на Github.",
        "Ваш кошелёк пустой,",
        "используйте Ваш адрес для получения.",
        "Ошибка соединения. Повтор...",
        "Актив разрешён",
        "Актив запрещён", // 110
        "Опции изменены",
        "Данные изменены",
        "Изменение последовательности",
        "Учётная запись объединена",
        "Ордер на продажу",
        "Отменить ордер на продажу",
        "Последовательная оплата",
        "Учётная запись для просмотра",
        "Данные не доступны.",
        "(24ч.)", // 120
        "Данные QR-кода скопированы в буфер обмена.",
        "Адрес скопирован в буфер обмена.",
        "Memo скопировано:",
        "Введите название домена-эмитента",
        "Подождите...",
        "Код:",
        "Эмитент актива:",
        "Описание:",
        "Условия:",
        "Люмены это собственный актив сети Stellar. Один люмен (XLM) это единица цифровой валюты, как и биткоин.", // 130
        "Количество люменов определяется фиксированными правилами на уровне протокола. Изначально созданное количество люменов было 100 миллиардов. Новые люмены не могут генерироваться произвольно кем-либо.",
        "Добавление отключено. Недостаточный XLM резерв.",
        "Эмитент:",
        "Мой адрес:",
        "Поделиться через",
        "Введите приватный ключ, публичный адрес или",
        "24-словную фразу восстановления для импорта учётной записи.",
        "Настройки учётной записи",
        "Сохранить Вашу фразу восстановления",
        "Переименовать учётную запись", // 140
        "Удалить учётную запись",
        "Вы уверены? Нажмите для подтверждения.",
        "Вы реально уверены?",
        "Последний шанс! Нажмите для удаления учётной записи.",
        "Удаление...",
        "Введите название новой учётной записи",
        "Котируемая валюта",
        "Импорт учётной записи",
        "Введите действительную учётную запись",
        "ИМПОРТ УЧЁТНОЙ ЗАПИСИ",//150
        "Импортирование: ",
        "Последние адреса",
        "Оплата получена: ",
        "Уведомления",
        "Всплывающие сообщения",
        "Получить Ваш дружеский адрес",
        "Рынок товаров",
        "Поделитесь своей любовью",
        "Помогите нам расти и оцените нас если Вам нравится Litemint!",
        "Пока не поддерживается!",
	"Покупка",
	"Продажа",
	"Торговля",
	"Список ордеров пуст.",
	"Цена",
	"Количество",
	"Последние операции",
	"Добавить актив",
	"Выбрать актив",
	"Ордеры",
	"Предложение",
	"Отменить предложение",
	"Отмена...",
        "Подтверждаете?",
        "Поместить ордер",
        "Всего:",
        "Посылаем ваш ордер, пожалуйста подождите...",
        "Транзакция не удалась.",
        "Ваш ордер был удачно помещён.",
        "Игры", // 180
        "ИГРЫ",
        "КОЛЛЕКЦИИ",
        "МАГАЗИН",
        "Скоро будет",
        "Лидеры",
        "Вы играете как 'Гость'. Получите свой Gamer ID!",
        "Игроков:",
   	"Обновляем цены...",
        "Цена не доступна",
        "Условия", // 190
        "Конфиденциальность",
        "Обновить цены",
        "Цены получены на основе лучших текущих цен Stellar DEX.",
        "Сайт продавца",
        "Поиск лучшей цены...",
        "Пожалуйста, подождите...",
        "Купить сейчас",
        "Цена",
        "Проверка",
        "Шоппинг", // 200
        "Благодарим за оплату!",
        "Обработка...",
        "Просмотр",
        "ПРИЛОЖЕНИЯ",
        "Выберите Ваш PIN.",
        "Подтвердите его.",
        "Готово.",
        "Можно торговать (DEX)",
        "Быстрый депозит с CoinSwitch",
        "Выберите объём депозита", // 210
        "Выберите валюту депозита",
        "Ещё...",
        "Вы получите:",
        "ПРОДОЛЖИТЬ",
        "Быстрый депозит",
        "Пополните Ваш аккаунт для покупки",
        "Проверка контракта NFT...",
        "Владелец",
        "Не владелец",
        "Ежедневно", // 220
        "За всё время",
        "Больше всех"
    ];

    /**
     * Language pack for Korean.
     * @member koreanLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const koreanLanguagePack = [
        "PIN 만들기",
        "PIN 입력",
        "PIN 확인",
        "로그인",
        "다음",
        "새로운 크립토월드를 경험하세요.",
        "PIN이 잘못되었습니다. 다시 시도하십시오.",
        "귀하의 PIN은 4-12 자입니다.",
        "추측하기 어려운 것을 선택하십시오.",
        "옵션",
        "계정 전환", // 10
        "계정 만들기",
        '계정 가져 오기',
        "언어 선택",
        "도움말 및 피드백",
        "잠시만 기다려주십시오.",
        "귀하의 계정을 로드 중입니다. 잠시만 기다려주십시오.",
        "계정",
        "귀하의 계정을 로드 중입니다. 잠시만 기다려주십시오.",
        "백업 단어를 저장하십시오",
        "24개의 단어를 종이에 적어주세요.", // 20
        "PIN 또는 기기를 분실 한 경우",
        "24개의 단어로 당신의 코인을 되 찾을 수 있습니다.",
        "승인",
        "스탭1",
        "스탭2",
        "완료",
        "다음 단계",
        "닫기",
        "같은 순서로 단어를 입력하십시오 (1-24).",
        "각 단어를 구분하는 데 공백을 사용하십시오", // 30
        "성공!",
        "실패!",
        "귀하의 백업 구문이 검증되지 않았습니다.",
        "귀하의 계정은 백업되지 않았습니다.",
        "1에서 24까지 모든 단어를 입력하세요.",
        "백업 구문 보안에 유의하세요!",
        "이 24 단어를 사용하여 코인을 회수하십시오.",
        "PIN또는 기기를 분실 한 경우 백업 단어를 사용하세요.",
        "Made with Love",
        "계정의 잔액", // 40
        "로딩 중 ...",
        "확인",
        "확인되지 않음",
        "보내기",
        "받기",
        "거래",
        "활동 로그",
        "토큰",
        "Reserve:",
        "계정의 잔액:", // 50
        "보내실 금액 :",
        "받으실 곳 주소 입력",
        "메모 입력 (선택)",
        "유효하지 않은 금액",
        "잘못된 주소",
        "사용 가능한 잔액:",
        "Sending:",
        "수수료:",
        "분 전",
        "분 전", // 60
        "몇 초 전",
        "추가",
        "추가되었습니다.",
        "삭제되었습니다.",
        "결제가 완료되었습니다.",
        "결제가 처리되지 않았습니다.",
        "주소를 한번 더 확인하세요.",
        "다시 시도하십시오.",
        "거래 영수증이 곧 제공될 것입니다.",
        "활동 목록에 추가하십시오.", // 70
        "파트너",
        "토큰 :",
        "또한 XLM 주소로 토큰을 받으실 수 있습니다.",
        "XLM 주소로 모든 종류의 토큰을 받으실 수 있습니다.",
        '주소를 복사하려면 누르십시오',
        "토큰 선택",
        "세부사항",
        "시세표",
        "공유하기",
        "웹사이트", // 80
        "토큰 삭제",
        '확인 됨',
        "신뢰할 수 있는 토큰",
        "잔액 > 0",
        "Payment Received",
        "Payment Sent",
        "Trades",
        "Trustlines",
        "다른",
        "로그아웃", // 90
        "계정관리",
        "개발자 :",
        "배포자 :",
        "라이센스 :",
        "종속성 라이선스",
        "경고",
        "거래에는 중대한 위험이 따르며 투자 자본 손실을 초래할 수 있습니다. 잃을 수 있는 것 이상 투자해서는 안되며 관련된 위험을 완전히 이해해야 합니다.",
        "법적 링크",
        "사용 기간",
        "개인 정보 보호 정책", // 100
        "도움말",
        "Support: ",
        "보안 :",
        "Github에서 보기",
        "이 프로젝트 소스 코드는 Github에서 확인할 수 있습니다.",
        "지갑이 비어 있습니다.",
        "지금 코인을 받아보세요.",
        "연결 오류. 다시 시도 중 ...",
        '토큰 허용됨',
        '허용되지 않는 토큰', // 110
        "옵션 변경됨",
        '데이터 변경됨',
        "Sequence Bumped",
        "계정합치기",
        "Sell Order",
        "Cancel Sell Order",
        "Path Payment",
        'Watch Only',
        "데이타 없음",
        "(24H)", // 120
        "QR 코드 데이터가 클립 보드로 복사되었습니다.",
        "주소가 클립 보드에 복사되었습니다.",
        "메모 복사 됨 :",
        "도메인 이름을 입력하세요.",
        "기다리세요",
        "토큰:",
        "발행계정:",
        "기술:",
        "컨디션:",
        "루멘는 스텔라 네트워크의 기본 자산이며 하나의 루멘(XLM)은 비트 코인과 같은 디지털 통화 단위입니다.", // 130
        "루멘 공급은 고정 된 프로토콜 수준의 규칙에 의해 결정되며, 현재 루멘 수는 500억개 입니다. 새로운 루멘은 임의로 생성 할 수 없습니다.",
        "코인이 충분하지 않습니다.",
        "발행계정:",
        "내 주소:",
        "공유:",
        "프라이빗 키 또는 공용 주소 또는",
        "24개의 백업 단어를 입력하십시오",
        "계정 설정",
        "백업 단어 저장",
        "계정 이름 변경", // 140
        "계정 삭제",
        "확실합니까? 확인하려면 누르십시오.",
        "다시한번 생각해 보세요",
        "마지막 기회! 탭하여 계정을 삭제하십시오.",
        "계정 삭제 중 ...",
        "새 계정 이름 입력",
        "Quote Currency",
        "계정 가져 오기",
        "유효한 계정을 입력하십시오.",
        "계정 가져 오기", // 150
        "계정: ",
        "최근 사용한 내역",
        "입금된 금액: ",
        "알림",
        "Toasts",
        "나만의 주소를 만들어보세요.",
        "마켓플레이스",
        "우리를 평가해라",
        "앱을 좋아하니? 우리를 평가해라!",
        "현재 지원되지 않음", // 160
        "구매",
        "판매",
        "무역",
        "주문 장이 비어 있습니다.",
        "가격",
        "양",
        "마지막 거래",
        "자산 추가",
        "자산 선택",
        "주문", // 170
        "제공",
        "취소 제안",
        "취소 중 ...",
        "확인?",
        "주문하기",
        "합계:",
        "주문 제출 중입니다 ...",
        "거래가 실패했습니다.",
        "주문이 성공적으로 제출되었습니다.",
        "게임", // 180
        "계략",
        "수집",
        "가게",
        "곧 출시 예정",
        "리더 보드",
        "'게스트'로 플레이 중입니다. 게이머 ID를 받으십시오!",
        "플레이어 :",
        "가격 갱신 중 ...",
        "가격이 없습니다",
        "용어", // 190
        "은둔",
        "가격 갱신",
        "가격은 Stellar DEX의 현재 최고 제안에서 계산됩니다.",
        "판매자 웹 사이트",
        "최고의 가격을 찾는 중 ...",
        "기다려주십시오 ...",
        "지금 구매",
        "가격",
        "점검",
        "쇼핑", // 200
        "지불 해 주셔서 감사합니다!",
        "처리 중 ...",
        "탐색",
        "앱",
        "PIN을 선택하십시오.",
        "확인하십시오.",
        "끝난.",
        "거래 가능 (DEX)",
        "CoinSwitch를 이용한 빠른 입금",
        "예금 금액 선택", // 210
        "예금 통화 선택",
        "더...",
        "받습니다 :",
        "계속하다",
        "빠른 예금",
        "구매할 계좌",
        "NFT 계약 확인 중 ...",
        "소유자",
        "소유자가 아님",
        "매일", // 220
        "항상",
        "ATH"
    ];

    /**
     * Language pack for Chinese.
     * @member chineseLanguagePack
     * @memberof Litemint.Pepper.Resources
     */
    const chineseLanguagePack = [
        "创建新 PIN",
        "输入您的 PIN",
        "再次输入 PIN",
        "登录",
        "下一步",
        "The crypto world is limitless, explore it.",
        "PIN不正确, 请重试。",
        "PIN 长度为 4-12 字符",
        "请确保密码足够复杂不易被猜测或撞对。",
        "选项",
        "切换账号", // 10
        "创建账号",
        "导入帐号",
        "选择语言",
        "帮助和反馈",
        "正在配置语言，请稍候...",
        "正在加载您的账号，请稍等...",
        "账号",
        "正在加载您的账号，请稍等...",
        "保存备份短语",
        "请抄录并妥善保存这24个单词。", // 20
        "如果你遗忘了密码或丢失了设备，",
        "这些备份短语用于恢复你的账号与资产。",
        "好的",
        "写入",
        "验证",
        "完成",
        "下一步",
        "关闭",
        "按顺序输入短语的单词(1-24).",
        "每个词用空格分隔开", //30
        "成功!",
        "失败!",
        "您未进行备份短语的验证。",
        "您的账号未备份。",
        "请确认您已按顺序记下24个备份短语的单词。",
        "妥善保管您的备份短语!",
        "使用备份短语(24个单词)恢复资产，",
        "若你遗忘了登录密码(PIN)。",
        "Made with love",
        "余额", // 40
        "载入中...",
        "已验证",
        "未验证",
        "发送",
        "接收",
        "交易",
        "活动",
        "资产",
        "保留:",
        "余额:", // 50
        "发送金额:",
        "输入发送目的地址",
        "输入备注(可选)",
        "无效金额",
        "无效地址",
        "可用余额:",
        "将发送至:",
        "手续费(Fee):",
        "一分钟前",
        "几分钟之前", // 60
        "几秒之前",
        "增加",
        "资产已添加",
        "资产已移除",
        "支付成功。",
        "支付失败。",
        "请检查目的地址",
        "并重试。",
        "本次交易",
        "很快将会保存(显示)在活动的列表中。", // 70
        "Partner",
        "接收的资产:",
        "您也可以使用 XLM 地址接收资产.",
        "您可以使用 XLM address 接受类型的资产.",
        "点击复制地址",
        "选择资产",
        "详细信息",
        "价格图",
        "分享",
        "网站", // 80
        "移除资产",
        "已验证",
        "可信的",
        "(显示)非零资产",
        "已接收款项",
        "已支付款项",
        "交易",
        "Trustlines",
        "其他",
        "退出登录", // 90
        "账号管理",
        "开发: ",
        "发行: ",
        "License: ",
        "依赖的 Licenses",
        "警告",
        "交易有风险，可能导致您的投资资金损失。确保您完全了解所涉及的风险，且不做出可能超出承受能力损失的投资。",
        "相关法令",
        "用户守则",
        "私隐政策", //100
        "帮助",
        "支持: ",
        "安全: ",
        "前往 Github",
        "此项目源码已在 Github",
        "您的钱包是空的，",
        "使用你的接收地址.",
        "连接服务器失败，正在重试...",
        "资产已接受",
        "资产不接受", // 110
        "选项已变更",
        "数据已变更",
        "Sequence Bumped",
        "账号合并",
        "卖单",
        "取消卖单",
        "Path Payment",
        "只读账号",
        "无可用数据",
        "(24H)", // 120
        "二维码内容已复制到剪贴板",
        "地址已复制到剪贴板",
        "已复制的备忘:",
        "输入发行人域名",
        "稍等...",
        "Code:",
        "资产发行人:",
        "描述:",
        "条件:",
        "Lumens 是基于 Stellar 网络的数字资产. lumen (XLM) 是其数字货币单位, 类似于比特币(bitcoin).", // 130
        "Lumen 供应量是稳定的, 协议级别的规定。初始量为1000亿(100 billion)。除此之外不为任何其他方式或人变更或产生发行量。.",
        "禁止增加。没有足够的 XLM。",
        "发行人:",
        "我的地址:",
        "分享通过",
        "输入私钥(private key),接收地址(public address) 或",
        "备份短语(24 words)导入账号。",
        "账户设置",
        "保存备份短语",
        "重命名账号", // 140
        "删除账号",
        "确认? 点击确认.",
        "真的确认?",
        "最终确认! 点击后账号将被删除.",
        "删除中...",
        "输入新账号名称",
        "Quote Currency",
        "导入账号",
        "输入有效账号",
        "导入账号",//150
        "重要: ",
        "最近的地址",
        "已收到的付款: ",
        "通知",
        "提示",
        "创建 Friendly Address",
        "卖场",
        "Give Us Some Love",
        "如果您觉得 Litemint 还不错，请给我们点赞好评素质三连!"
    ];

    /**
     * Language pack for Greek.
     * @member greekLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const greekLanguagePack = [
        "Δημιουργία νέου PIN",
        "Εισαγάγετε το PIN σας",
        "Επιβεβαιώστε το PIN σας",
        "Εισέλθετε",
        "Επόμενο",
        "Ο κόσμος του κρύπτο είναι απεριόριστος, εξερευνείτε το.",
        "Λανθασμένο PIN. Δοκιμάστε ξανά.",
        "Το PIN σας μπορεί να είναι 4-12 ψηφία.",
        "Βεβαιωθείτε ότι επιλέξατε ένα που είναι δύσκολο να μαντέψει.",
        "Επιλογές",
        "Αλλαγή λογαριασμών", // 10
        "Δημιουργήστε λογαριασμό",
        "Εισαγωγή λογαριασμού",
        "Επιλογή γλώσσας",
        "Βοήθεια & ανατροφοδότηση",
        "Ρύθμιση γλώσσας... Παρακαλώ περιμένετε...",
        "Φόρτωση του λογαριασμού σας, παρακαλώ περιμένετε...",
        "Λογαριασμός",
        "Φόρτωση του λογαριασμού σας, παρακαλώ περιμένετε...",
        "ΑΠΟΘΗΚΕΥΣΤΕ ΤΟ ΑΝΤΙΓΡΑΦΟ ΤΗΣ ΑΣΦΑΛΕΙΑΣ ΣΑΣ",
        "Καταγράψτε αυτές τις 24 λέξεις σε ένα χαρτί.", // 20
        "Εάν χάσετε το PIN σας ή τη συσκευή σας",
        "αυτές οι λέξεις σας επιτρέπουν να επαναφέρετε τα κεφάλαιά σας.",
        "Καλά",
        "Αποθηκεύστε τα",
        "Επαληθεύστε τα",
        "Τελειώσαμε",
        "Επόμενο βήμα",
        "Κλείσιμο",
        "Πληκτρολογήστε τις λέξεις σας με την ίδια σειρά (1-24).",
        "Χρησιμοποιήστε κενό για να διαχωρίσετε την κάθε λέξη", //30
        "ΕΠΙΤΥΧΩΣ!",
        "ΑΠΕΤΥΧΕ!",
        "Το αντίγραφο ασφαλείας φράσης σας δεν επικυρώθηκε.",
        "Ο λογαριασμός σας δεν έχει αντίγραφο ασφαλείας.",
        "Βεβαιωθείτε ότι γράψατε όλες τις λέξεις από 1 έως 24.",
        "Κρατήστε το αντίγραφο ασφαλείας φράσης σας μυστικό!",
        "Χρησιμοποιήστε αυτές τις 24 λέξεις για να επαναφέρετε τα κεφάλαιά σας",
        "σε περίπτωση απώλειας ή ξεχασμένου PIN.",
        "Κατασκευασμένο με αγάπη",
        "Υπόλοιπο", // 40
        "Φόρτωση...",
        "Επαληθευμένο",
        "Μη επαληθευμένο",
        "Αποστολή",
        "Αποδοχή",
        "Εμπόριο",
        "Δραστηριότητες",
        "Στοιχεία",
        "Αποθεματικό:",
        "Υπόλοιπο:", // 50
        "Ποσό προς αποστολή:",
        "Εισαγάγετε τη διεύθυνση προορισμού",
        "Εισαγάγετε τη memo (προαιρετικό)",
        "Μη έγκυρο ποσό",
        "Μη έγκυρη διεύθυνση",
        "Διαθέσιμο υπόλοιπο:",
        "Στέλνετε:",
        "Τέλη:",
        "πριν από ένα λεπτό",
        "λεπτά πριν", // 60
        "Πριν από μερικά δευτερόλεπτα",
        "Προσθήκη",
        "Το στοιχείο προστέθηκε",
        "Το στοιχείο αφαιρέθηκε",
        "Η πληρωμή σας ήταν επιτυχής.",
        "Η πληρωμή σας δεν ήταν επιτυχής.",
        "Επαληθεύστε την διεύθυνση προορισμού",
        "και προσπαθήστε ξανά.",
        "Η απόδειξη συναλλαγής θα προστεθεί",
        "σύντομα στη Λίστα Δραστηριοτήτων.", // 70
        "Συνεργάτης",
        "Το στοιχείο για την παραλαβή:",
        "Μπορείτε επίσης να λάβετε αυτό το στοιχείο με τη διεύθυνση XLM σας.",
        "Μπορείτε να λάβετε οποιοδήποτε στοιχείο με τη διεύθυνση XLM σας.",
        "Πατήστε για να αντιγράψετε τη διεύθυνση",
        "Επιλογή στοιχείου",
        "Λεπτομέριες",
        "Διάγραμμα τιμών",
        "Κοινή χρήση",
        "Ιστοσελίδα", // 80
        "Κατάργηση στοιχείου",
        "Επαληθευμένο",
        "Εμπιστο",
        "Μη μηδενικό υπόλοιπο",
        "Η πληρωμή ελήφθη",
        "Η πληρωμή έχει σταλεί",
        "Συναλλαγές",
        "Σχέσεις εμπιστοσύνης",
        "Αλλα",
        "Αποσύνδεση", // 90
        "Διαχείριση λογαριασμού",
        "Αναπτύχθηκε από: ",
        "Διανέμεται από: ",
        "Η άδεια: ",
        "Εξαρτώμενες Αδειες",
        "Προειδοποίηση",
        "Το εμπόριο συνεπάγεται σημαντικό κίνδυνο και μπορεί να έχει ως αποτέλεσμα την απώλεια του επενδεδυμένου κεφαλαίου σας. Δεν πρέπει να επενδύσετε περισσότερο από ό, τι μπορείτε να αντέξετε οικονομικά να χάσετε και θα πρέπει να διασφαλίσετε ότι κατανοείτε πλήρως τους σχετικούς κινδύνους.",
        "Νομικοί σύνδεσμοι",
        "Οροι χρήσης",
        "Πολιτική απορρήτου", //100
        "Βοήθεια",
        "Υποστήριξη: ",
        "Ασφάλεια: ",
        "Προβολή στο Github",
        "Ο πηγαίος κώδικας αυτού του έργου είναι διαθέσιμος στο Github.",
        "Το πορτοφόλι σας είναι άδειο,",
        "χρησιμοποιήστε τη διεύθυνση παραλαβής σας.",
        "Σφάλμα σύνδεσης. Επανάληψη...",
        "Επιτρεπόμενο στοιχείο",
        "Μη επιτρεπόμενο στοιχείο", // 110
        "Επιλογές άλλαξαν",
        "Τα δεδομένα άλλαξαν",
        "Σειρά προχώρησε",
        "Ο λογαριασμός συγχωνεύθηκε",
        "Εντολή πώλησης",
        "Ακύρωση εντολής πώλησης",
        "Πληρωμή με διαδρομή",
        "Ο λογαριασμός είναι μόνο για προβολή",
        "Χωρίς διαθέσιμα δεδομένα.",
        "(24ωρο)", // 120
        "Τα δεδομένα του κώδικα QR αντιγράφηκαν στο πρόχειρο.",
        "Η διεύθυνση αντιγράφηκε στο πρόχειρο.",
        "Memo αντιγράφηκε:",
        "Εισαγάγετε το όνομα τομέα του εκδότη",
        "Περιμένετε...",
        "Κώδικας:",
        "Εκδότης του στοιχείου:",
        "Περιγραφή:",
        "Συνθήκες:",
        "Τα Lumens είναι το εγγενές στοιχείο του δικτύου Stellar. Ένα lumen (XLM) είναι μια μονάδα ψηφιακού νομίσματος, όπως ένα bitcoin.", // 130
        "Ο εφοδιασμός των Lumen καθορίζεται από σταθερούς κανόνες σε επίπεδο πρωτοκόλλου. Ο αριθμός των Lumen που δημιουργήθηκαν στη γένεση ήταν 100 δισεκατομμύρια.Τα νέα Lumens δεν μπορούν να δημιουργηθούν αυθαίρετα από κανέναν.",
        "Η προσθήκη είναι απενεργοποιημένη. Δεν υπάρχει αρκετό απόθεμα των XLM.",
        "Εκδότης:",
        "Η διεύθυνσή μου:",
        "Κοινή χρήση μέσω",
        "Εισαγάγετε ένα ιδιωτικό κλειδί, μια δημόσια διεύθυνση ή",
        "ένα αντίγραφο ασφαλείας φράσης 24 λέξεων για εισαγωγή ενός λογαριασμού.",
        "Ρυθμίσεις λογαριασμού",
        "Αποθήκευση του αντιγράφου ασφαλείας φράσης σας",
        "Μετονομασία λογαριασμού", // 140
        "Διαγραφή λογαριασμού",
        "Είστε βέβαιοι; Πατήστε για επιβεβαίωση.",
        "Είστε πραγματικά σίγουροι;",
        "Τελευταία ευκαιρία! Πατήστε για να διαγράψετε το λογαριασμό.",
        "Διαγραφή...",
        "Εισαγάγετε νέο όνομα λογαριασμού",
        "Δευτερεύον νομισματική μονάδα",
        "Εισαγωγή λογαριασμού",
        "Εισαγάγετε έναν έγκυρο λογαριασμό",
        "ΕΙΣΑΓΩΓΗ ΛΟΓΑΡΙΑΣΜΟΥ",//150
        "Εισαγωγή: ",
        "Πρόσφατες διευθύνσεις",
        "Η πληρωμή ελήφθη: ",
        "Ειδοποιήσεις",
        "Αναδυόμενα μηνύματα",
        "Αποκτήστε τη φιλική σας διεύθυνση",
        "Αγορά",
        "Μοιραστείτε την αγάπη σας",
        "Βοηθήστε μας να μεγαλώσουμε και να μας βαθμολογήσετε εάν απολαμβάνετε το Litemint!",
        "Δεν υποστηρίζεται ακόμα!",
	"Αγορές",
	"Πωλήσεις",
	"Συναλλαγή",
	"Το βιβλίο παραγγελιών είναι κενό.",
	"Τιμή",
	"Ποσό",
	"Τελευταίες συναλλαγές",
	"Προσθήκη στοιχείου",
	"Επιλογή στοιχείου",
	"Παραγγελίες",
	"Προσφορά",
	"Ακύρωση προσφοράς",
	"Ακύρωση...",
        "Επιβεβαιώνετε;",
        "Παραγγέλνω",
        "Σύνολο:",
        "Υποβολή της παραγγελίας σας, παρακαλώ περιμένετε...",
        "Η συναλλαγή απέτυχε.",
        "Η παραγγελία σας υποβλήθηκε επιτυχώς.",
     	"Παιχνίδια", // 180
        "ΠΑΙΧΝΙΔΙΑ",
        "ΣΥΛΛΕΚΤΙΚΑ",
        "ΜΑΓΑΖΙ",
        "Ερχεται συντομα",
        "Οί Νικητές",
        "Παίζετε ως 'Guest'. Πάρτε το Gamer ID! σας",
        "Παίκτες:"
    ];

	
    /**
     * List of language packs.
     * @member languagePacks
     * @memberof Litemint.Pepper.Resources
    */
    namespace.Pepper.Resources.languagePacks = {
        "en": { "name": "English", "text": englishLanguagePack },
        "fr": { "name": "Français", "text": frenchLanguagePack },
        "de": { "name": "Deutsch", "text": germanLanguagePack },
        "ru": { "name": "Русский", "text": russianLanguagePack, "scale": 0.95 },
        "kr": { "name": "한국어", "text": koreanLanguagePack },
        "cn": { "name": "中文(中国)", "text": chineseLanguagePack },
	"el": { "name": "Ελληνικά", "text": greekLanguagePack, "scale": 0.95 }
    };

    /**
     * Default language.
     * @member defaultLanguage
     * @memberof Litemint.Pepper.Resources
    */
    namespace.Pepper.Resources.defaultLanguage = "en";

})(window.Litemint = window.Litemint || {});
