/**
 * @overview Litemint Pepper resources languages implementation.
 * @copyright 2018-2019 Frederic Rezeau.
 * @copyright 2018-2019 Litemint LLC.
 * @license [MIT]{@link https://github.com/litemint/litemint/blob/master/LICENSE}
 */

(function (namespace) {
    "use strict";

    /**
     * Language pack for English.
     * @member englishLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const englishLanguagePack = [
        "Create New PIN",
        "Enter your PIN",
        "Confirm your PIN",
        "Sign In",
        "Next",
        "The crypto world is limitless, explore it.",
        "Incorrect PIN. Please try again.",
        "Your PIN can be 4-12 digits.",
        "Make sure you choose one that's hard to guess.",
        "Options",
        "Switch accounts", // 10
        "Create account",
        "Import account",
        "Select language",
        "Help & feedback",
        "Configuring language. Please wait...",
        "Loading your account. Please wait...",
        "Account",
        "Loading your account. Please wait...",
        "SAVE YOUR BACKUP PHRASE",
        "Please write down these 24 words on a paper.", // 20
        "If you lose your PIN or device",
        "these words allow you to restore your funds.",
        "OK",
        "Write",
        "Verify",
        "Finish",
        "Next Step",
        "Close",
        "Type your words in the same order (1-24).",
        "Use a space to separate each word", //30
        "SUCCESS!",
        "FAILED!",
        "Your backup phrase was not validated.",
        "Your account is not backed-up.",
        "Make sure you write all words from 1 to 24.",
        "Keep your backup phrase secret!",
        "Use these 24 words to recover your funds",
        "in case of loss or forgotten PIN.",
        "Made with love",
        "Balance", // 40
        "Loading...",
        "Verified",
        "Unverified",
        "Send",
        "Receive",
        "Trade",
        "Activity",
        "Assets",
        "Reserve:",
        "Balance:", // 50
        "Amount to send:",
        "Enter your destination address",
        "Enter your memo (optional)",
        "Invalid Amount",
        "Invalid Address",
        "Available balance:",
        "You are sending:",
        "Fee:",
        "minute ago",
        "minutes ago", // 60
        "Few seconds ago",
        "Add",
        "Asset Added",
        "Asset Removed",
        "Your payment was successful.",
        "Your payment was not successful.",
        "Verify the destination address",
        "and try again.",
        "The transaction receipt will shortly",
        "be added to the Activity List.", // 70
        "Partner",
        "Asset to receive:",
        "You can also receive this asset with your XLM address.",
        "You can receive any asset with your XLM address.",
        "Tap to copy address",
        "Select Asset",
        "Details",
        "Price Chart",
        "Share",
        "Website", // 80
        "Remove Asset",
        "Verified",
        "Trusted",
        "Non-zero Balance",
        "Payment Received",
        "Payment Sent",
        "Trades",
        "Trustlines",
        "Other",
        "Sign Out", // 90
        "Manage Account",
        "Developed by: ",
        "Distributed by: ",
        "License: ",
        "Dependency Licenses",
        "Warning",
        "Trading involves significant risk and can result in the loss of your invested capital. You should not invest more than you can afford to lose and should ensure that you fully understand the risks involved.",
        "Legal Links",
        "Term of Use",
        "Privacy Policy", //100
        "Help",
        "Support: ",
        "Security: ",
        "View on Github",
        "This project source code is available on Github.",
        "Your wallet is empty,",
        "Time to nag your friends.",
        "Connection error. Retrying...",
        "Asset Allowed",
        "Asset Disallowed", // 110
        "Options Changed",
        "Data Changed",
        "Sequence Bumped",
        "Account Merged",
        "Sell Order",
        "Cancel Sell Order",
        "Path Payment",
        "Watch Only Account",
        "No Data Available.",
        "(24H)", // 120
        "The QR code data was copied to clipboard.",
        "The address was copied to clipboard.",
        "Memo Copied:",
        "Enter issuer domain name",
        "Wait...",
        "Code:",
        "Asset Issuer:",
        "Description:",
        "Conditions:",
        "Lumens are the native asset of the Stellar network. One lumen (XLM) is a unit of digital currency, like a bitcoin.", // 130
        "Lumen supply is determined by fixed, protocol-level rules. The number of lumens created at genesis was 100 billion. Every year, there is a 1% inflation rate. New lumens cannot be generated arbitrarily by anyone.",
        "Adding disabled. Not enough XLM reserve.",
        "Issuer:",
        "My Address:",
        "Share via",
        "Enter a private key, public address or",
        "24-word backup phrase to import an account.",
        "Account Settings",
        "Save your backup phrase",
        "Rename Account", // 140
        "Delete Account",
        "Are you sure? Tap to confirm.",
        "Are you really sure?",
        "Last chance! Tap to delete account.",
        "Deleting...",
        "Enter new account name",
        "Quote Currency",
        "Import Account",
        "Enter a valid account",
        "IMPORT AN ACCOUNT",//150
        "Importing: ",
        "Recent Addresses",
        "Payment Received: ",
        "Notifications",
        "Toasts",
        "Get Your Friendly Address",
        "Marketplace"
    ];

    /**
     * Language pack for French.
     * @member frenchLanguagePack
     * @memberof Litemint.Pepper.Resources
    */
    const frenchLanguagePack = [
        "Créer un nouveau code PIN",
        "Entrez votre code PIN",
        "Confirmez votre code PIN",
        "Se connecter",
        "Suivant",
        "Pour un monde crypto sans limite, à explorer.",
        "Code PIN incorrect. Veuillez réessayer.",
        "Votre code PIN peut être composé de 4 à 12 chiffres.",
        "Assurez-vous d'en choisir un difficile à deviner.",
        "Options",
        "Changer de compte",
        "Créer un compte",
        "Importer un compte",
        "Choisir la langue",
        "Aide et commentaires",
        "Configuration de la langue. Veuillez patienter ...",
        "Chargement de votre compte. Veuillez patienter ...",
        "Compte",
        "Chargement de votre compte. Veuillez patienter ...",
        "SAUVEZ VOTRE PHRASE SECRETE",
        "S'il vous plaît écrivez ces 24 mots sur un papier.",
        "Si vous perdez votre code PIN ou votre appareil",
        "Ces mots vous permettent de restaurer vos fonds.",
        "OK",
        "Écrire",
        "Vérifier",
        "Terminer",
        "Etape suivante",
        "Fermer",
        "Tapez vos mots dans le même ordre (1-24).",
        "Utilisez un espace pour séparer chaque mot",
        "SUCCÈS!",
        "ÉCHEC!",
        "Votre phrase de sauvegarde n'a pas été validée.",
        "Votre compte n'est pas sauvegardé.",
        "Assurez-vous d'écrire tous les mots de 1 à 24.",
        "Gardez votre phrase de sauvegarde secrète!",
        "Utilisez ces 24 mots pour récupérer vos fonds",
        "en cas de perte ou de code PIN oublié.",
        "Made with Love",
        "Balance",
        "Chargement...",
        "Vérifié",
        "Non vérifié",
        "Envoyer",
        "Recevoir",
        "Commerce",
        "Activité",
        "Tokens",
        "Réserve:",
        "Balance:",
        "Montant à envoyer:",
        "Entrez votre adresse de destination",
        "Entrez votre mémo (facultatif)",
        "Montant invalide",
        "Adresse invalide",
        "Solde disponible:",
        "Vous envoyez:",
        "Frais:",
        "Il y a une minute",
        "Il y a quelques minutes",
        "Il y a quelques secondes",
        "Ajouter",
        "Token Ajouté",
        "Token supprimé",
        "Votre paiement a réussi.",
        "Votre paiement a échoué.",
        "Vérifier l'adresse de destination",
        "et essayez à nouveau.",
        "Le reçu de transaction sera bientôt",
        "ajouté à la liste des activités.",
        "Partenaire",
        "Token à recevoir:",
        "Vous pouvez également recevoir ce token avec votre adresse XLM.",
        "Vous pouvez recevoir n'importe quel token avec votre adresse XLM.",
        "Tapez pour copier l'adresse",
        "Sélectionner un token",
        "Détails",
        "Diagramme",
        "Partager",
        "Site Web",
        "Supprimer le token",
        "Vérifié",
        "De confiance",
        "Solde non nul",
        "Paiement reçu",
        "Paiement envoyé",
        "Echanges",
        "Trustline",
        "Autre",
        "Déconnexion",
        "Gérer son compte",
        "Développé par: ",
        "Distribué par: ",
        "Licence: ",
        "Licences des dépendances",
        "Attention",
        "Les transactions comportent des risques importants et peuvent entraîner la perte de votre capital investi. Vous ne devez pas investir plus que ce que vous pouvez vous permettre de perdre et vous devez vous assurer de bien comprendre les risques encourus.",
        "Liens juridiques",
        "Conditions d'utilisation",
        "Politique de confidentialité",
        "Aide",
        "Soutien: ",
        "Sécurité: ",
        "Voir sur Github",
        "Le code source du projet est disponible sur Github.",
        "Votre portefeuille est vide",
        "Partagez votre addresse avec vos amis.",
        "Erreur de connexion. Nouvelle tentative ...",
        "Token autorisé",
        "Token refusé",
        "Options changées",
        "Données modifiées",
        "Séquence Bumped",
        "Compte fusionné",
        "Ordre de vente",
        "Annuler l'offre de vente",
        "Path Payment",
        "Compte Watch Only",
        "Pas de données disponibles.",
        "(24H)",
        "Les données du code QR ont été copiées dans le presse-papier.",
        "L'adresse a été copiée dans le presse-papier.",
        "Mémo Copié:",
        "Nom de domaine",
        "Attendez...",
        "Code:",
        "Emetteur du Token:",
        "Description:",
        "Conditions:",
        "Les lumens sont le token natif du réseau Stellar. Un lumen (XLM) est une unité de monnaie numérique, similaire au bitcoin.",
        "Le nombre de lumens créés lors de la genèse était de 100 milliards. Chaque année, il y a un taux d'inflation de 1%. Les nouveaux lumens ne peuvent être générés arbitrairement.",
        "Ajout désactivé. Pas assez de réserve XLM.",
        "Emetteur:",
        "Mon adresse:",
        "partage via",
        "Entrez une clé privée, une addresse publique ou",
        "votre phrase secrète pour importer le compte.",
        "Paramètres du compte",
        "Sauvez votre phrase secrète",
        "Renommez votre compte",
        "Supprimez votre compte",
        "Etes-vous sure? Confirmez.",
        "Etes-vous vraiment sure?",
        "Dernière chance! Confirmez.",
        "Suppression...",
        "Etrez un nouveau nom",
        "Quote Currency",
        "Importez un compte",
        "Entrez un compte valide",
        "IMPORTEZ UN COMPTE",
        "Importation: ",
        "Addresses Récentes",
        "Payment Reçu: ",
        "Notifications",
        "Toasts",
        "Obtenez une Friendly Address",
        "Commerce"
    ];

    /**
     * List of language packs.
     * @member languagePacks
     * @memberof Litemint.Pepper.Resources
    */
    namespace.Pepper.Resources.languagePacks = {
        "en": { "name": "English", "text": englishLanguagePack },
        "fr": { "name": "Français", "text": frenchLanguagePack }
    };

    /**
     * Default language.
     * @member defaultLanguage
     * @memberof Litemint.Pepper.Resources
    */
    namespace.Pepper.Resources.defaultLanguage = "en";

})(window.Litemint = window.Litemint || {});
